#!/usr/bin/python3

import argparse
from subprocess import run
import sys


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--fontsize", type=int, default=20)
    parser.add_argument("--output", default="image.png")
    parser.add_argument("--font", default="IPAゴシック")
    parser.add_argument("--color", default="black")
    ns = parser.parse_args()

    text = sys.stdin.read()

    if text.startswith(" "):
        text = "\\" + text
    if text.endswith("\n"):
        text = text[:-1]

    run(["convert",  # ImageMagick
         "-font", ns.font,
         "-pointsize", str(ns.fontsize),
         "-fill", ns.color,
         "label:" + text,
         ns.output],
        check=True)


if __name__ == "__main__":
    main()
